# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Foodie-Kazooie' do
  use_frameworks!

  # Pods for Foodie-Kazooie
  pod 'Alamofire', '~> 5.0.0-rc.1'  #Networking
  pod 'OHHTTPStubs/Swift'           #Mocks of response
  pod 'lottie-ios'                  #Animation
  pod 'Hero'                        #Animation
  pod 'fluid-slider'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 5.0'
  
  target 'Foodie-KazooieTests' do
    inherit! :search_paths
  end

end
